package io.jettra.wui.core.annotations;

import java.util.List;
import java.util.Map;

/**
 * Interface generated by Annotation Processor to handle CRUD operations without reflection.
 */
public interface CrudHandler<M> {
    List<M> findAll();
    void save(M model);
    void delete(String id);
    String getIdValue(M item);
    Map<String, String> getJsonMap(M item);
    M createInstance();
    void updateFields(M model, Map<String, String> data);
}
